version: '2'
services:
  postgres_host:
    image: postgres:10-alpine
    restart: always
    ports: ["5433:5432"]
  postgres-client:
    build:
      context: ./client
    depends_on:
      - postgres_host
    tty: true
    environment:
      - APP_POSTGRES_HOST=postgres_host
      - APP_POSTGRES_PORT=5432
    volumes:
      - ../scripts:/srv
      - ../data:/data
    links: [postgres_host]
  notebook:
    build:
      context: ./notebook
    depends_on:
      - postgres_host
    environment:
      - APP_POSTGRES_HOST=postgres_host
      - APP_POSTGRES_PORT=5432
    ports: ["8888:8888"]
    links: [postgres_host]
    volumes:
      - ../notebooks:/home/jovyan/work
      - ../data:/home/jovyan/data
    environment:
      - APP_POSTGRES_HOST=postgres_host
      - APP_POSTGRES_PORT=5432
      - USE_HTTPS=yes
